export const home = {
    state:{
        hotSearch:[
            {
                name:'JAVA',
                path:''
            },
            {
                name:'IOS',
                path:''
            },
            {
                name:'数据',
                path:''
            },
            {
                name:'安全',
                path:''
            },
            {
                name:'搜索',
                path:''
            },
            {
                name:'算法',
                path:''
            },
            {
                name:'运营',
                path:''
            },
            {
                name:'视觉',
                path:''
            },
            {
                name:'交互',
                path:''
            },
            {
                name:'前端',
                path:''
            },
        ],
        newJobs:[
            {
                title:'盒马-餐饮采购专家-上海',
                address:'上海',
                time:'10分钟前', // 正式情况下可能为时间戳，需要转换计算相对时间
                path:'/',
                href:'/'
            },
            {
                title:'新零售技术事业群-Java/C++研发-淘系技术部',
                address:'杭州',
                time:'12分钟前',
                path:'/',
                href:'/'
            },
            {
                title:'蚂蚁集团-软件安全资深专家',
                address:'杭州',
                time:'13分钟前',
                path:'/',
                href:'/'
            },
            {
                title:'菜鸟-Country Customs Operation Expert-Russia',
                address:'莫斯科',
                time:'30分钟前',
                path:'/',
                href:'/'
            },
            {
                title:'盒马-B2C采购专家-西安',
                address:'西安',
                time:'35分钟前',
                path:'/',
                href:'/'
            },
            {
                title:'政务钉钉事业部-资深政务行业运营专家-杭州',
                address:'杭州',
                time:'1小时前',
                path:'/',
                href:'/'
            },
            {
                title:'口碑-公司治理资深法务专员-法务部',
                address:'杭州',
                time:'1小时前',
                path:'/',
                href:'/'
            },
            {
                title:'蚂蚁金服-区块链跨境贸易金融高级产品专家-智能科技',
                address:'上海,杭州',
                time:'2小时前',
                path:'/',
                href:'/'
            }
        ]
    },
    reducers:{

    },
    effects: (dispatch) => ({
        
    })
}